2. Filtering Data
========================
--Retrieve rows with a specific condition using WHERE.
SELECT ENAME,JOB,SAL 
FROM EMP
WHERE ENAME ='KING';

--Use comparison operators (>, <, >=, <=, =).
SELECT ENAME,JOB,SAL 
FROM EMP
WHERE SAL =5000;

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE SAL < 5000;

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE SAL <= 5000;

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE SAL > 4000;

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE SAL >= 4000;
--Use BETWEEN to filter data within a range.

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE SAL BETWEEN 4000 AND 5000;
--Use IN to filter data within a list.

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE SAL IN(3000,5000);


SELECT ENAME,JOB,SAL 
FROM EMP
WHERE JOB IN('ANALYST','IT');

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE ENAME IN('KING','CLARK','SMITH');

--Filter data using the LIKE operator and wildcards (%, _).

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE ENAME LIKE 'KI%';

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE JOB NOT LIKE 'PRE%';

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE JOB  LIKE 'PRE%';

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE JOB LIKE 'I_';

SELECT ENAME,JOB,SAL 
FROM EMP
WHERE ENAME LIKE 'MART__';


SELECT ENAME,JOB,SAL 
FROM EMP
WHERE ENAME NOT LIKE 'MART__';