3. Sorting Data
===============================
--Sort data in ascending order using ORDER BY.
SELECT ENAME,JOB,SAL 
FROM EMP 
ORDER BY SAL;


SELECT ENAME,JOB,SAL 
FROM EMP 
ORDER BY ENAME;

SELECT ENAME,JOB,SAL 
FROM EMP 
ORDER BY JOB ;

--Sort data in descending order.

SELECT ENAME,JOB,SAL 
FROM EMP 
ORDER BY SAL DESC;

SELECT ENAME,JOB,SAL 
FROM EMP 
ORDER BY JOB DESC;

SELECT ENAME,JOB,SAL 
FROM EMP 
ORDER BY ENAME DESC;

--Sort by multiple columns.
SELECT ENAME,JOB,SAL 
FROM EMP 
ORDER BY ENAME,JOB,SAL DESC;

--Sort by a computed column.

SELECT ENAME,JOB,SAL,(SAL * 12) AS ANNUAL_SALARY
FROM EMP 
ORDER BY SAL*12 ;

SELECT ENAME,JOB,SAL,(SAL * 12) AS ANNUAL_SALARY
FROM EMP 
ORDER BY SAL*12 DESC ;


SELECT ENAME,JOB,SAL,(SAL * 12) AS ANNUAL_SALARY
FROM EMP 
ORDER BY ANNUAL_SALARY ;

SELECT ENAME,JOB,SAL,(SAL * 12) AS ANNUAL_SALARY
FROM EMP 
ORDER BY ANNUAL_SALARY DESC;



SELECT ENAME, JOB, ANNUAL_SALARY
FROM (
    SELECT ENAME, JOB,(SAL * 12) AS ANNUAL_SALARY 
    FROM EMP
) SUBQUERY
ORDER BY ANNUAL_SALARY DESC;


SELECT ENAME, JOB, ANNUAL_SALARY
FROM (
    SELECT ENAME, JOB,(SAL * 12) AS ANNUAL_SALARY 
    FROM EMP
) SUBQUERY
ORDER BY ANNUAL_SALARY ;